# Ensemble Blending

In [1]:
import pandas as pd

In [ ]:
xgb_sub = pd.read_csv('submission.csv')
rf_sub = pd.read_csv('submission_rf.csv')

In [ ]:

blend = xgb_sub.copy()
blend['Heart Disease'] = (xgb_sub['Heart Disease'] + rf_sub['Heart Disease']) / 2



blend.head()

       id  Heart Disease
0  630000            1.0
1  630001            0.0
2  630002            1.0
3  630003            0.0
4  630004            0.0

In [5]:
# Convert probabilities back to binary if necessary (since the predictions might be 0.5 now)
# Any score >= 0.5 becomes 1 (Heart Disease Presence), else 0
blend['Heart Disease'] = (blend['Heart Disease'] >= 0.5).astype(int)

blend.head()

       id  Heart Disease
0  630000              1
1  630001              0
2  630002              1
3  630003              0
4  630004              0

In [6]:
# Save the final blended submission
blend.to_csv('submission_blend.csv', index=False)
print("Saved blended predictions to submission_blend.csv")

Saved blended predictions to submission_blend.csv